/*
Nome: Guilherme Henrique Ferreira de Oliveira 
Matrícula: 54883
Lista: 2
Exercício: 5
*/

#include <stdio.h>
#include <stdlib.h>

void realloc_hits(int **hits_array, int *hit_ticket, int cont);
void print_hits(int *hit);

int get_num(int *num) {
	for(size_t i = 0; i < 6; i++) {
		if(scanf("%d", num+i) != 1) return 0;
	}
	return 1;
}

void error_rnumber() {
	puts("Failed to read a number!");
	exit(1);
}

void hits(int *glot, int *gticket) {
	int cont = 0;
	int *hits = NULL;
	for(size_t i = 0; i < 6; i++) {
		for(size_t j = 0; j < 6; j++) {
			if(*(gticket+i) == *(glot+j)) {
				realloc_hits(&hits, (gticket+i), cont);
				cont++;
			}
		}
	}
	puts("Final Report:");
		for (int k = 0; k < cont; k++) {
    		print_hits((hits+k)); 
	}
	free(hits);
}

void realloc_hits(int **hits_array, int *hit_ticket, int cont) {
	int *temp= (int *) realloc(*hits_array, (cont+1) * sizeof(int));
	if(temp == NULL) {
		puts("Allocation error!");
		exit(1);
	}	

	*hits_array = temp;
	(*hits_array)[cont] = *hit_ticket;
	
}

void print_hits(int *hit) {
	printf("Hits: %d\n", *hit);
}

int main() {
	int gen_lot[6];
	int gen_ticket[6];
	puts("Generated by the lottery: ");
	if(!get_num(gen_lot)) {
		error_rnumber();
	}
	puts("Ticket number: ");
	if(!get_num(gen_ticket)) {
		error_rnumber();
	}

	hits(gen_lot, gen_ticket);
	return 0;
}
